//unique-ish tags per scenario so the shared customElements registry never sees a redefinition
export const TAGS = {
	simple: "ssr-simple",
	withAttrs: "ssr-with-attrs",
	asyncPreYield: "ssr-async-pre-yield",
	falsePositive: "ssr-false-positive-guard",
	multiInstance: "ssr-multi-instance",
	customSentinel: "ssr-custom-sentinel",
	unmarked: "ssr-unmarked",
	noSentinel: "ssr-no-sentinel",
	loadSingle: "ssr-load-single",
	loadShared: "ssr-load-shared",
	wideWebApi: "ssr-wide-web-api",
	neverYields: "ssr-never-yields",
	quotedAttrs: "ssr-quoted-attrs",
	closedRoot: "ssr-closed-root",
	slotted: "ssr-slotted",
	slotCounting: "ssr-slot-counting",
	nestedChild: "ssr-nested-child",
	commented: "ssr-commented",
	selfNesting: "ssr-self-nesting",
	excluded: "ssr-excluded",
	undefinedTag: "ssr-never-defined",
} as const;
